#!/bin/bash

# Ubuntu Illumini Dotfiles Installer
# Based on the README.md configuration

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log() {
  echo -e "${BLUE}[INFO]${NC} $1"
}

warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

success() {
  echo -e "${GREEN}[OK]${NC} $1"
}

error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running on Ubuntu/Debian
if [ ! -f /etc/debian_version ]; then
  error "This script is intended for Ubuntu/Debian based systems."
  exit 1
fi

log "Starting installation of Ubuntu Illumini Dotfiles configuration..."

# 1. System Update & Dependencies
log "Updating system and installing dependencies..."
sudo apt update
sudo apt install -y git curl wget unzip fontconfig python3-pip zsh build-essential

# 2. Shell & Terminal (Zsh, Oh My Zsh, Starship)
log "Setting up Shell (Zsh, Oh My Zsh, Starship)..."

# Install Oh My Zsh if not present
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
else
  warn "Oh My Zsh already installed."
fi

# Install Starship
if ! command -v starship &>/dev/null; then
  curl -sS https://starship.rs/install.sh | sh -s -- -y
else
  warn "Starship already installed."
fi

# Install Zsh Plugins
ZSH_CUSTOM=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}
mkdir -p "$ZSH_CUSTOM/plugins"

clone_plugin() {
  local repo=$1
  local name=$(basename "$repo")
  if [ ! -d "$ZSH_CUSTOM/plugins/$name" ]; then
    git clone "https://github.com/$repo" "$ZSH_CUSTOM/plugins/$name"
  else
    warn "Plugin $name already installed."
  fi
}

clone_plugin "zsh-users/zsh-autosuggestions"
clone_plugin "zsh-users/zsh-syntax-highlighting"
clone_plugin "marlonrichert/zsh-autocomplete"

# Install Atuin
if ! command -v atuin &>/dev/null; then
  curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh
fi

# Configure .zshrc
log "Configuring .zshrc..."
cat >"$HOME/.zshrc" <<EOF
# Generated by Illumini Dotfiles Installer

export ZSH="\$HOME/.oh-my-zsh"

ZSH_THEME="" # Starship handles the prompt

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-autocomplete
)

source \$ZSH/oh-my-zsh.sh

# Starship
eval "\$(starship init zsh)"

# Atuin
eval "\$(atuin init zsh)"

# FastFetch on startup
if command -v fastfetch &> /dev/null; then
    fastfetch
fi
EOF

# 3. Terminal Tools (FastFetch, Btop)
log "Installing Terminal Tools..."
sudo apt install -y fastfetch btop

# 4. Editor (Neovim + LazyVim)
log "Setting up Neovim and LazyVim..."

# Install Neovim (Check version, if old, maybe suggest snap or ppa, but sticking to apt for safety)
sudo apt install -y neovim

# Backup existing config
if [ -d "$HOME/.config/nvim" ]; then
  warn "Backing up existing Neovim config to ~/.config/nvim.bak"
  mv "$HOME/.config/nvim" "$HOME/.config/nvim.bak"
fi

# Clone LazyVim Starter
git clone https://github.com/LazyVim/starter "$HOME/.config/nvim"
# Remove .git to make it a user config
rm -rf "$HOME/.config/nvim/.git"

# 5. Fonts (FiraCode Nerd Font)
log "Installing FiraCode Nerd Font..."
FONT_DIR="$HOME/.local/share/fonts"
mkdir -p "$FONT_DIR"
if [ ! -f "$FONT_DIR/FiraCodeNerdFont-Regular.ttf" ]; then
  wget -O /tmp/FiraCode.zip https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
  unzip -o /tmp/FiraCode.zip -d "$FONT_DIR"
  rm /tmp/FiraCode.zip
  fc-cache -fv
else
  warn "FiraCode Nerd Font seems to be installed."
fi

# 6. Applications
log "Installing Applications (Kew, Feh, GitHub CLI)..."
sudo apt install -y kew feh gh

# 7. GNOME Extensions (Best Effort)
log "Installing GNOME Extensions tools..."
sudo apt install -y gnome-shell-extensions gnome-shell-extension-manager pipx
pipx ensurepath

# Attempt to install gnome-extensions-cli to help user
if ! command -v gnome-extensions-cli &>/dev/null; then
  pipx install gnome-extensions-cli --system-site-packages
fi

log "Installing GNOME Extensions (requires session restart to take full effect)..."
# List of extensions from README
# PaperWM, Tiling Assistant, Blur My Shell, OpenBar, Hide System Icons, Just Perfection, Clipboard Indicator, Media Controls, Quick Settings Tweaks, Workspace Indicator
# Note: This might fail if gnome-extensions-cli isn't working perfectly or UUIDs changed.
EXTENSIONS=(
  "paperwm@paperwm.github.com"
  "tiling-assistant@leleat-on-github"
  "blur-my-shell@aunetx"
  "openbar@neuromorph"
  "hidetopbar@mathieu.bidon.ca" # Approximation for Hide System Icons
  "just-perfection-desktop@just-perfection"
  "clipboard-indicator@tudmotu.com"
  "mediacontrols@cliffniff.github.com"
  "quick-settings-tweaks@atareao.es"
  "workspace-indicator@gnome-shell-extensions.gcampax.github.com"
)

if command -v gnome-extensions-cli &>/dev/null; then
  for ext in "${EXTENSIONS[@]}"; do
    log "Installing extension: $ext"
    gext install "$ext" || warn "Failed to install $ext (might need manual install)"
  done
else
  warn "gnome-extensions-cli not found. Please install these extensions manually: ${EXTENSIONS[*]}"
fi

# 8. Bootloader (GRUB)
log "Downloading GRUB Theme (Minecraft)..."
if [ ! -d "$HOME/double-minegrub-menu" ]; then
  git clone https://github.com/Lxtharia/double-minegrub-menu "$HOME/double-minegrub-menu"
  warn "GRUB theme downloaded to $HOME/double-minegrub-menu."
  warn "Please run the install script inside that directory manually to avoid breaking bootloader automatically."
else
  warn "GRUB theme directory already exists."
fi

# 9. Finalizing
log "Changing default shell to Zsh..."
sudo chsh -s $(which zsh) $USER

success "Installation complete!"
echo -e "${YELLOW}IMPORTANT STEPS REMAINING:${NC}"
echo "1. Restart your computer or log out/in to apply GNOME extensions and Shell changes."
echo "2. Open Neovim ('nvim') to let LazyVim install plugins."
echo "3. Run the GRUB theme installer in $HOME/double-minegrub-menu if you want the Minecraft theme."
echo "4. Configure your GNOME extensions via 'Extension Manager' app."
echo "5. Enjoy your new setup!"
